-- 코드를 입력하세요
SELECT p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE p
    JOIN REST_REVIEW r 
    ON p.MEMBER_ID = r.MEMBER_ID 
WHERE p.MEMBER_ID = (SELECT MEMBER_ID
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT (MEMBER_ID) DESC LIMIT 1)
    
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT